### PR TITLE
Tech Debt - swap unicode characters.

### PR DESCRIPTION
**Pull request by dataswifty**
I replaced all of the unicode characters using the following commands.

find . -name "*.scala" | xargs perl -pi -e 's/→/->/g'
find . -name "*.scala" | xargs perl -pi -e 's/←/<-/g'
find . -name "*.scala" | xargs perl -pi -e 's/⇒/=>/g'

### CODE REVIEW

**Comment by benshaw** [comment]
I thought we were using a scala style thingy to implement this ?

**Comment by dataswifty** [comment]
> I thought we were using a scala style thingy to implement this ?

I don't know how we will agree on that and wanted to get rid of these glyphs ASAP. :)

**Comment by benshaw** [comment]
I think everything you had on the styling was great apart from function method arity

**Comment by dataswifty** [comment]
This pr uses no scalafmt, only the shell commands.  There are no logic changes.

**Pull request merged**
