### PR TITLE
Update Docker Base Image

### PR DESCRIPTION
**Pull request by benshaw**
* move to openjdk:15-alpine
* stick with alpine as it creates a much smaller container
* apline appears to be good security wise
* the JRE is no longer packaged seperately
* ISSUE: https://dswift.atlassian.net/browse/DS-228?atlOrigin=eyJpIjoiNWViYjhkNzRiYzhmNDYyMDhkYTI0MWU0MTFlYzZiMTgiLCJwIjoiaiJ9

### CODE REVIEW

**Comment by benshaw** [comment]
There is no alpine version for JDK 11 and all the other options create quite large containers
The best option would be buster-slim (debian) and this would be quite large

The options i could find where

JDK15 & Alpine - OpenJdk official release
JDK11 & Slim - OpenJdk official release

There is potentially some unofficial release as well
The best information i could find is https://stackoverflow.com/questions/53375613/why-is-the-java-11-base-docker-image-so-large-openjdk11-jre-slim

**Comment by benshaw** [comment]
official images available https://github.com/docker-library/openjdk

**Comment by dataswifty** [comment]
https://hub.docker.com/layers/openjdk/library/openjdk/11.0.7-slim/images/sha256-3971bb05b4272196d2e32a144360981101a277c8286cbae9ca7ed660411de168?context=explore is ~220megs

**Comment by benshaw** [comment]
the alpine image is ~60 so that is a big difference but i don't see any other option
I didnt realize JDK15 wasn't officially released yet

**Comment by benshaw** [comment]
makes the HAT project 351MB

**Comment by benshaw** [comment]
DS-228 #time 1h #transition CODE REVIEW

**Pull request merged**
